#!/usr/bin/env python3
"""Verify the shipped Unity native-plugin tree.

This exists because of a real packaging failure: the ``arm64-v8a`` and
``x86_64`` ``.so.meta`` files claimed ``CPU: ARMv7`` and were enabled for every
platform. Unity accepted that silently, and the resulting build shipped an
ARM64 library labelled ARMv7 while also handing an Android ``.so`` to the
Editor. Nothing failed until the game did, on a device.

The checks are deliberately independent of Unity:

* every ``.meta`` declares exactly one enabled platform, with the CPU that its
  directory name implies;
* Android libraries are never enabled for Editor, Windows, Linux, or macOS;
* every asset GUID is unique and non-zero;
* when the binaries are present, each ELF's machine type matches its ABI
  directory, and each exports the full C ABI symbol list, including every
  symbol frozen at ABI 1.0.

Run with no arguments from the repository root. Exits non-zero on any problem
and prints one line per finding.
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

# Directory suffix -> (Android CPU, enabled-platform set, ELF e_machine).
ANDROID_PLUGINS = {
    "Android/arm64-v8a/libcb2vec.so": ("ARM64", 0xB7),
    "Android/armeabi-v7a/libcb2vec.so": ("ARMv7", 0x28),
    "Android/x86_64/libcb2vec.so": ("X86_64", 0x3E),
}
WINDOWS_PLUGIN = "x86_64/cb2vec.dll"

# e_machine values, for a readable message when one does not match.
ELF_MACHINES = {0x28: "ARM (32-bit)", 0x3E: "x86-64", 0xB7: "AArch64", 0x03: "x86"}


def parse_meta(path: Path) -> dict:
    """Parse the small, regular subset of Unity meta YAML we emit.

    Returns ``{"guid": str, "platforms": {name: {"enabled": bool, "CPU": str}}}``.
    A hand-rolled parser keeps this script dependency-free; the files are
    generated by us, so the shape is known.
    """
    guid = None
    platforms: dict[str, dict] = {}
    current: str | None = None
    pending_first = False
    in_settings = False

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        stripped = line.strip()
        if stripped.startswith("guid:"):
            guid = stripped.split(":", 1)[1].strip()
            continue
        if stripped == "- first:":
            pending_first = True
            in_settings = False
            continue
        if pending_first and stripped.endswith(":") is False and ":" in stripped:
            key, value = (part.strip() for part in stripped.split(":", 1))
            key = key.strip("'\"")
            # "Standalone: Win64" -> "Standalone:Win64"; "'': Any" -> "Any".
            current = f"{key}:{value}" if key else value
            platforms.setdefault(current, {"enabled": False, "CPU": None})
            pending_first = False
            continue
        if stripped.startswith("enabled:") and current:
            platforms[current]["enabled"] = stripped.split(":", 1)[1].strip() == "1"
            continue
        if stripped.startswith("settings:"):
            in_settings = True
            continue
        if in_settings and current and stripped.startswith("CPU:"):
            platforms[current]["CPU"] = stripped.split(":", 1)[1].strip()
            continue
    return {"guid": guid, "platforms": platforms}


def elf_machine(path: Path) -> int | None:
    """Return the ELF e_machine field, or None if this is not an ELF file."""
    with path.open("rb") as handle:
        header = handle.read(20)
    if len(header) < 20 or header[:4] != b"\x7fELF":
        return None
    return struct.unpack_from("<H", header, 18)[0]


def elf_dynamic_symbols(path: Path) -> set[str]:
    """Extract defined dynamic symbol names from a 32- or 64-bit little-endian ELF."""
    data = path.read_bytes()
    if data[:4] != b"\x7fELF":
        raise ValueError(f"{path} is not an ELF file")
    is_64 = data[4] == 2

    if is_64:
        e_shoff, = struct.unpack_from("<Q", data, 0x28)
        e_shentsize, e_shnum = struct.unpack_from("<HH", data, 0x3A)
    else:
        e_shoff, = struct.unpack_from("<I", data, 0x20)
        e_shentsize, e_shnum = struct.unpack_from("<HH", data, 0x2E)

    sections = []
    for index in range(e_shnum):
        base = e_shoff + index * e_shentsize
        if is_64:
            sh_type, = struct.unpack_from("<I", data, base + 4)
            sh_offset, sh_size = struct.unpack_from("<QQ", data, base + 0x18)
            sh_link, = struct.unpack_from("<I", data, base + 0x28)
            sh_entsize, = struct.unpack_from("<Q", data, base + 0x38)
        else:
            sh_type, = struct.unpack_from("<I", data, base + 4)
            sh_offset, sh_size = struct.unpack_from("<II", data, base + 0x10)
            sh_link, = struct.unpack_from("<I", data, base + 0x18)
            sh_entsize, = struct.unpack_from("<I", data, base + 0x24)
        sections.append((sh_type, sh_offset, sh_size, sh_link, sh_entsize))

    names: set[str] = set()
    for sh_type, sh_offset, sh_size, sh_link, sh_entsize in sections:
        if sh_type != 11 or sh_entsize == 0:  # SHT_DYNSYM
            continue
        _, str_offset, str_size, _, _ = sections[sh_link]
        strtab = data[str_offset:str_offset + str_size]
        for entry in range(sh_size // sh_entsize):
            base = sh_offset + entry * sh_entsize
            st_name, = struct.unpack_from("<I", data, base)
            st_shndx, = struct.unpack_from("<H", data, base + (0x06 if is_64 else 0x0E))
            if st_name == 0 or st_shndx == 0:  # unnamed or undefined
                continue
            end = strtab.index(b"\x00", st_name)
            names.add(strtab[st_name:end].decode("ascii"))
    return names


def check_meta(problems: list[str], meta: Path, expect_android_cpu: str | None) -> str | None:
    """Validate one plugin meta. Returns its GUID."""
    parsed = parse_meta(meta)
    guid = parsed["guid"]
    platforms = parsed["platforms"]
    rel = meta.as_posix()

    if not guid or set(guid) == {"0"} or len(guid) != 32:
        problems.append(f"{rel}: guid must be 32 hex characters and non-zero, got {guid!r}")

    android = platforms.get("Android:Android", {})
    editor = platforms.get("Editor:Editor", {})
    win64 = platforms.get("Standalone:Win64", {})
    linux64 = platforms.get("Standalone:Linux64", {})
    osx = platforms.get("Standalone:OSXUniversal", {})
    any_platform = platforms.get("Any", {})

    if any_platform.get("enabled"):
        problems.append(f"{rel}: 'Any Platform' must be disabled")

    if expect_android_cpu is not None:
        if not android.get("enabled"):
            problems.append(f"{rel}: Android must be enabled")
        actual = android.get("CPU")
        if actual != expect_android_cpu:
            problems.append(
                f"{rel}: Android CPU is {actual!r}, expected {expect_android_cpu!r}"
            )
        for name, entry in (("Editor", editor), ("Windows x86_64", win64),
                            ("Linux64", linux64), ("macOS", osx)):
            if entry.get("enabled"):
                problems.append(
                    f"{rel}: {name} must be disabled for an Android library"
                )
    else:
        if android.get("enabled"):
            problems.append(f"{rel}: Android must be disabled for a Windows DLL")
        if not editor.get("enabled"):
            problems.append(f"{rel}: Editor must be enabled")
        if editor.get("CPU") != "x86_64":
            problems.append(
                f"{rel}: Editor CPU is {editor.get('CPU')!r}, expected 'x86_64'"
            )
        if not win64.get("enabled"):
            problems.append(f"{rel}: Standalone Win64 must be enabled")
        for name, entry in (("Linux64", linux64), ("macOS", osx)):
            if entry.get("enabled"):
                problems.append(f"{rel}: {name} must be disabled for a Windows DLL")
    return guid


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--plugins",
        default="unity/Assets/Plugins",
        type=Path,
        help="Path to the Assets/Plugins directory to verify.",
    )
    parser.add_argument(
        "--symbols",
        default="include/cb2vec.symbols",
        type=Path,
        help="Expected exported C symbols, one per line.",
    )
    parser.add_argument(
        "--abi10-symbols",
        default="include/cb2vec.symbols.abi10",
        type=Path,
        help="Symbols frozen at ABI 1.0 that must never disappear.",
    )
    parser.add_argument(
        "--require-binaries",
        action="store_true",
        help="Fail if a native library is missing rather than skipping its checks.",
    )
    args = parser.parse_args()

    problems: list[str] = []
    guids: dict[str, str] = {}

    expected_symbols = {
        line.strip()
        for line in args.symbols.read_text(encoding="utf-8").splitlines()
        if line.strip()
    }
    abi10_symbols = {
        line.strip()
        for line in args.abi10_symbols.read_text(encoding="utf-8").splitlines()
        if line.strip()
    }
    missing_from_current = abi10_symbols - expected_symbols
    if missing_from_current:
        problems.append(
            "ABI 1.0 symbols dropped from the current export list: "
            + ", ".join(sorted(missing_from_current))
        )

    targets = [(rel, cpu, machine) for rel, (cpu, machine) in ANDROID_PLUGINS.items()]
    targets.append((WINDOWS_PLUGIN, None, None))

    for rel, cpu, machine in targets:
        meta = args.plugins / (rel + ".meta")
        if not meta.is_file():
            problems.append(f"missing meta file: {meta}")
            continue
        guid = check_meta(problems, meta, cpu)
        if guid:
            if guid in guids:
                problems.append(
                    f"duplicate GUID {guid} in {meta} and {guids[guid]}"
                )
            else:
                guids[guid] = str(meta)

        binary = args.plugins / rel
        if not binary.is_file():
            if args.require_binaries:
                problems.append(f"missing native library: {binary}")
            continue
        if machine is None:
            continue  # Windows DLL: architecture is checked by the build itself.

        actual_machine = elf_machine(binary)
        if actual_machine != machine:
            problems.append(
                f"{binary}: ELF machine is "
                f"{ELF_MACHINES.get(actual_machine, hex(actual_machine or 0))}, expected "
                f"{ELF_MACHINES[machine]}"
            )
        exported = elf_dynamic_symbols(binary)
        cb2vec_exported = {name for name in exported if name.startswith("cb2vec_")}
        missing = expected_symbols - cb2vec_exported
        if missing:
            problems.append(f"{binary}: missing exports {', '.join(sorted(missing))}")
        extra = cb2vec_exported - expected_symbols
        if extra:
            problems.append(f"{binary}: unexpected exports {', '.join(sorted(extra))}")
        missing_abi10 = abi10_symbols - cb2vec_exported
        if missing_abi10:
            problems.append(
                f"{binary}: ABI 1.0 symbols missing: {', '.join(sorted(missing_abi10))}"
            )

    if problems:
        print(f"Unity plugin verification failed ({len(problems)} problem(s)):")
        for problem in problems:
            print(f"  - {problem}")
        return 1

    checked = "meta files"
    if any((args.plugins / rel).is_file() for rel, _, _ in targets):
        checked += ", ELF architectures, and exported symbols"
    print(f"Unity plugin verification passed ({checked}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
